package src;
public enum Value {
    ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE,
    DRAW_1, DRAW_5, REVERSE, SKIP, SKIP_EVERYONE, FLIP, WILD,WILD_DRAW_2, WILD_DRAW_COLOR, DRAW_ONE, DRAW_FIVE, WILD_DRAW_TWO, NO_MORE_CARDS;

    private Value(){

    }
}
